# Generated by Django 4.2.18 on 2025-02-02 00:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writersarchive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Story',
        ),
    ]
