# Generated by Django 4.2.18 on 2025-02-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0005_alter_story_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_on']},
        ),
    ]
