# Generated by Django 4.2.18 on 2025-02-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0006_alter_comment_options_alter_story_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='posted_on',
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=2),
        ),
    ]
