# Generated by Django 4.2.18 on 2025-02-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0007_remove_story_posted_on_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Action & Adventure'), (1, 'Comedy'), (2, 'Contemporary'), (3, 'Fantasy'), (4, 'Historical'), (5, 'Horror'), (6, 'Mystery'), (7, 'Romance'), (8, 'Science Fiction')], default=2),
        ),
    ]
