# Generated by Django 4.2.18 on 2025-02-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0008_alter_story_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='body',
        ),
    ]
