# Generated by Django 4.2.18 on 2025-02-10 17:45

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0009_rename_comment_text_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='writersarchive.story')),
            ],
        ),
    ]
