# Generated by Django 4.2.18 on 2025-02-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0010_genrecoverimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrecoverimage',
            options={'ordering': ['genre']},
        ),
    ]
