# Generated by Django 4.2.18 on 2025-02-10 18:33

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0011_alter_genrecoverimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrecoverimage',
            options={'ordering': ['genre_list']},
        ),
        migrations.RemoveField(
            model_name='genrecoverimage',
            name='genre',
        ),
        migrations.AddField(
            model_name='genrecoverimage',
            name='genre_list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='writersarchive.story', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
