# Generated by Django 4.2.18 on 2025-02-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0012_alter_genrecoverimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrecoverimage',
            name='genre_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='writersarchive.story'),
        ),
    ]
