# Generated by Django 4.2.18 on 2025-02-10 19:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0013_alter_genrecoverimage_genre_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrecoverimage',
            options={'ordering': ['genre']},
        ),
        migrations.RemoveField(
            model_name='genrecoverimage',
            name='genre_list',
        ),
        migrations.AddField(
            model_name='genrecoverimage',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Action & Adventure'), (1, 'Comedy'), (2, 'Contemporary'), (3, 'Fantasy'), (4, 'Historical'), (5, 'Horror'), (6, 'Mystery'), (7, 'Romance'), (8, 'Science Fiction')], default=2, unique=True),
        ),
        migrations.AlterField(
            model_name='genrecoverimage',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='writersarchive.genrecoverimage'),
        ),
    ]
