# Generated by Django 4.2.18 on 2025-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0014_alter_genrecoverimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='cover_img',
        ),
        migrations.AlterField(
            model_name='genrecoverimage',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Adventure'), (1, 'Comedy'), (2, 'Contemporary'), (3, 'Fantasy'), (4, 'Historical'), (5, 'Horror'), (6, 'Mystery'), (7, 'Romance'), (8, 'Science Fiction')], unique=True),
        ),
    ]
