# Generated by Django 4.2.18 on 2025-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0015_remove_story_cover_img_alter_genrecoverimage_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrecoverimage',
            name='genre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
