# Generated by Django 4.2.18 on 2025-02-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writersarchive', '0016_alter_genrecoverimage_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('Not Rated', 0), ('★', 1), ('★★', 2), ('★★★', 3), ('★★★★', 4), ('★★★★★', 5)], default='Not Rated'),
        ),
    ]
